#!/usr/bin/python

dna = "AAAACCCGGT" # sample
dna = "CATTAATAATGATATCTTCTTGGCTCAAGTAGACGAGTGTATACGTCCTAGCGACTTCATCACGTTAGCGATCAAGCAGTGTAACCCTTGGGGGAACGTCGGGTAGAAGGTGACTGAAACAAGCTGGGTTGTCTTTACTCTTAGACGTGTAAAGCATGAAACGTTACTTCAGCTTCTTTTGGCCCACGCGATAAGCGGTATTTTACGGCCGAAGCCTCTCGAGCTGGATGTCGCGAGTTGGGCCGCCGCTTATTGGCAGTGTGACTTTTCCGGGGACGGCGCTGCAGATAGTTGGCAGCTGTTTGAGTGTAAGAACGAGAATTGGGGAGTGATGCCGGAAACGATGGACAATGAGCCGGGGCCCAGCAAGGAGGAGTCTGCGTGTTACATCACGAGCTGCACAGCTCTCGGAACTTTACGCACTCGACATGCTTGATTCTTCTGCCCAATACGCTAAGCACGCGCAGGCCGACTTACTTACCTTCTGCAATTTCGCATGTAGAGGCGTGCTGTAACCTATAAAAGTGTAATATCCGGAAGTTCCGAGGCCAGGCCTGAGATCACAGTGTTGCGGATGGCTCCCAACAGTACAATTTAAAACCGAGCATCTCCAGCTAACTGGCCACGGACGATCATCTCCGAACCCCTCCCGTTTAGGAACTCGTAGCATACACTTAGGGGGGTCGCAATGGGTGATCCTGAACGACGCGGTGCTAGTGAATGTTGATGCTGGGACCGACGACCCTTAGCGACTAATCGCCTACCCATCTATACACTACACTTAAGCAAACAGTGCCGCCGAACTCTTACATATCTTGTTCAACGCCCGCTGTTGCATCGATTGGTTGCTGCGGCAAAGACGCTAACATCCGTTTAGCCCAAATCACGTCGTGCGAG"
result = ""

for c in dna:
  if c == 'A':
    result = 'T' + result
  elif c =='T':
    result = 'A' + result
  elif c == 'C':
    result = 'G' + result
  elif c == 'G':
    result = 'C' + result

print result

